// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiXVTqjzjDGKHqRua-xxbSjroGaAW93Yk',
    appId: '1:47404386324:web:30f18682e28e292a2dbf01',
    messagingSenderId: '47404386324',
    projectId: 'todo-ee8d4',
    authDomain: 'todo-ee8d4.firebaseapp.com',
    storageBucket: 'todo-ee8d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMUZCB6KFkmF_tt2V_krcr1MTZVPMh47w',
    appId: '1:47404386324:android:81251630866276c52dbf01',
    messagingSenderId: '47404386324',
    projectId: 'todo-ee8d4',
    storageBucket: 'todo-ee8d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu6SGcQFRnGrJVFnpANOd01S_jyNx8rcc',
    appId: '1:47404386324:ios:a254b174e066dd7a2dbf01',
    messagingSenderId: '47404386324',
    projectId: 'todo-ee8d4',
    storageBucket: 'todo-ee8d4.appspot.com',
    iosClientId: '47404386324-ugpl3mrsa3rnf7ihhdgqjih4u1s8c605.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu6SGcQFRnGrJVFnpANOd01S_jyNx8rcc',
    appId: '1:47404386324:ios:a254b174e066dd7a2dbf01',
    messagingSenderId: '47404386324',
    projectId: 'todo-ee8d4',
    storageBucket: 'todo-ee8d4.appspot.com',
    iosClientId: '47404386324-ugpl3mrsa3rnf7ihhdgqjih4u1s8c605.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
